### ISSUE TITLE
Implement the PKModel class

### ISSUE THREAD

**Issue by simonlichtinger** [simonlichtinger/pkmodel_group7#6]
This will:

- [] implement the PKModel class in pkmodel.py
- [] set up testing functionality

**Comment by simonlichtinger** [comment]
TODO: edit to make compatible with template functions

**Comment by AndrewKirby1** [comment]
Just FYI testing coverage for pkmodel.py is ~90%
https://codecov.io/gh/simonlichtinger/pkmodel_group7/src/issue-03-yaml-update/pkmodel/pkmodel.py
This webpage should highlight the lines of code which are missed by the unit testing

**Comment by simonlichtinger** [comment]
Merged and made compatible with functions
